# Generated by Django 2.0.7 on 2018-07-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180719_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'My subscriber', 'verbose_name_plural': 'A lot of subscribers'},
        ),
    ]
